---
- hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: installing packages
      apt: "name={{ item }} state=installed"
      with_items:
        - git
        - wget
        - curl
        - vim
        - tree
